"""empty message

Revision ID: 1a3692031901
Revises: 
Create Date: 2019-09-11 16:51:54.812430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3692031901'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.create_unique_constraint(None, 'todos', ['id'])
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'todos', type_='unique')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
